packages:
  - codepen/*
  - studies/*
  - tools/*

catalog:
  '@types/react': 19.2.14
  '@types/react-dom': 19.2.3
  react: 19.2.5
  react-dom: 19.2.5
  vite: 8.0.8
engineStrict: true
minimumReleaseAge: 2880
saveExact: true
shellEmulator: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3
